package com.loomi.desafiotech.orders.domain.enums;

public enum Failure {
    OUT_OF_STOCK,
    WAREHOUSE_UNAVAILABLE,

    SUBSCRIPTION_LIMIT_EXCEEDED,
    DUPLICATE_ACTIVE_SUBSCRIPTION,
    INCOMPATIBLE_SUBSCRIPTIONS,

    LICENSE_UNAVAILABLE,
    ALREADY_OWNED,
    DISTRIBUTION_RIGHTS_EXPIRED,

    PRE_ORDER_SOLD_OUT,
    RELEASE_DATE_PASSED,
    INVALID_RELEASE_DATE,

    CREDIT_LIMIT_EXCEEDED,
    INVALID_CORPORATE_DATA,
    PENDING_MANUAL_APPROVAL,

    PAYMENT_FAILED,
    FRAUD_SUSPECTED,
    PRODUCT_NOT_AVAILABLE,
    UNKNOWN_ERROR
}
